In [11]:
import numpy as np
from scipy.linalg import lu
import matplotlib.pyplot as plt

# 2.45

# 2.48
$$A=LU$$

where $\boldsymbol{L}$ is unit lower triangular and $\boldsymbol{U}$ is upper triangular. Given such a factorization, the linear system $A x=b$ can be written as $L U x=b$ and hence can be solved by first solving the lower triangular system $L y=b$ by forward-substitution, then the upper triangular system $U x=y$ by back-substitution.

# 2.49

## (1)
$$
L P x=b
$$
where now $L$ really is lower triangular. To solve the linear system, we first solve the lower triangular system $\boldsymbol{L} y=\boldsymbol{P} \boldsymbol{b}$ by forward-substitution, then $x = P^T y$

## (2)
$$
P L x=b
$$
where now $L$ really is lower triangular. To solve the linear system, we solve the lower triangular system $\boldsymbol{L} x=\boldsymbol{P}^T \boldsymbol{b}$ by forward-substitution.

## 2.51
$ x = (1.5,1.5),y=(2,0)$
$$ \|x\|_1=3>2=\|y\|_1$$
$$\|x\|_{\infty}=1.5<2=\|y\|_{\infty}$$

# 2.52

$\|A\|_1$更容易计算

# 2.53
## (1)
$cond(A)=\|A\|_1 \|A^{-1}\|_1 = 6 \times 0.5 = 3$
## (2)
$cond(A)=\|A\|_{\infty} \|A^{-1}\|_{\infty} = 6\times 0.5=3$

# 2.61
(a)(c) well-conditioned
(b)(d) ill-conditioned

# 2.77
A 的 cholesky分解为：
$$\left[\begin{array}{ll}
2 & 0 \\
1 & 1
\end{array}\right]$$

In [12]:
A = np.array([[4,2],[2,2]])
np.linalg.cholesky(A)

array([[2., 0.],
       [1., 1.]])

# 2.10
## (1)
$$ P = P_n\cdots P_2P_1$$
$$ P^{-1} = (P_n\cdots P_2P_1)^{-1} = P_1^{-1} P_2^{-1}\cdots  P_n^{-1}=P_1P_2\cdots P_n=P_1P_2\cdots P_n=P_1^TP_2^T\cdots P_n^T=(P_n\cdots P_2P_1)^{T}=P^T$$
## (2)
$$ P A= P(M_{n-1} P_{n-1} \cdots M_{1} P_{1})^{-1}U=P(P_1M_1^{-1}P_2\cdots P_nM_n^{-1})U$$
即证明
$ P(P_1M_1^{-1}P_2\cdots P_nM_n^{-1})$为下三角矩阵。
$$
    \begin{aligned}
        P(P_1M_1^{-1}P_2\cdots P_nM_n^{-1}) & =P_n\cdots P_2P_1 P_1M_1^{-1}P_2\cdots P_nM_n^{-1},                               \\
               & =P_n\cdots P_2M_1^{-1}P_2\cdots P_nM_n^{-1}              \\
                   & =P_n\cdots P_2(I+m_1e_1)P_2\cdots P_nM_n^{-1} ,
    \end{aligned}
$$
由于$P_2(I+m_1e_1)P_2=I+m_1'e_1$(由于$P_2$只对第二行以及以后的行做变换,$m_1'$即为对应两个元素交换所得)，考虑$(I+m_1'e_1)(I+m_2e_2)=I+\sum_{i=1}^2m_ie_i$,其也为下三角。

长此以往，可得$P(P_1M_1^{-1}P_2\cdots P_nM_n^{-1})$也为下三角矩阵。

# 2.31
- $\|x\|_A=(x^TAx)^{\frac{1}{2}}=(x^TL L^Tx)=(y^Ty)=\sum_i y_i^2>=0$ (A positive defined), And $\|x\|_A=0$ if and only if $y = x = 0$
- $\|\alpha x\|_A=(\alpha^2 x^TAx)^{\frac{1}{2}}=\alpha (x^TAx)^{\frac{1}{2}} = \alpha \|x\|_A$
- $\|x+y\|_A = $

In [13]:
def pivot_matrix(M,j):

    m = M.shape[0]
                                                            
    id_mat = np.eye(m)                         
    row = max(range(j, m), key=lambda i: abs(M[i][j]))
    # print(row)
    if j != row:                                                                          
        id_mat[[j,row],:]= id_mat[[row,j],:]
    return id_mat, row
    
def LU_Decomposition(A,pivot = False):
    N = A.shape[0]
    A_copy = A.copy()

    L = np.eye(N)
    U = np.zeros((N,N))
    P = np.eye(N)
    for i in range(N):
        if pivot:
            tmp_P,row = pivot_matrix(A_copy,i)
            P = tmp_P@P
            A_copy = tmp_P@A_copy
            L[[i,row],i-1] = L[[row,i],i-1]
        L[i:,i] = A_copy[i:,i]/A_copy[i,i]
        # print(i,A[i,i])
        U[i,i:] = A_copy[i,i:]
        A_copy[i:,i:] = A_copy[i:,i:] - L[i:,i][:,None]@U[i,i:][None,:]
        # print(A,L[i:,i].reshape([-1,1]).shape,U[i,i:].shape)
    if pivot:
        return P,L,U
    return L,U


In [14]:
A= np.array([[1,1,-1], [1,2,-2.],[-2,1,1]])
L,U = LU_Decomposition(A)
print(L,U)

[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-2.  3.  1.]] [[ 1.  1. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  2.]]


In [15]:
A_1= np.array([[1,1,-1], [1,2,-2.],[-2,3,1]])
pivot_matrix(A_1,1)

(array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]),
 2)

In [16]:
a = np.array([[ 1. , 0.,  0.],
 [ 1. , 1.,  0.],
 [-2. , 3.,  1.]])
b = np.array([[ 1. , 1. ,-1.],
 [ 0.,  1., -1.],
 [ 0. , 0.,  2.]])

In [17]:
a@b ==A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
lu(A)

(array([[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.28571429,  1.        ,  0.        ,  0.        ],
        [ 0.71428571,  0.12      ,  1.        ,  0.        ],
        [ 0.71428571, -0.44      , -0.46153846,  1.        ]]),
 array([[ 7.        ,  5.        ,  6.        ,  6.        ],
        [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
        [ 0.        ,  0.        , -1.04      ,  3.08      ],
        [ 0.        ,  0.        ,  0.        ,  7.46153846]]))

In [19]:
p,l,u=LU_Decomposition(A,pivot=True)
np.allclose(A - p.T @ l @ u, np.zeros((4, 4)))

True

In [20]:
LU_Decomposition(A,pivot=True)

(array([[0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.28571429,  1.        ,  0.        ,  0.        ],
        [ 0.71428571,  0.12      ,  1.        ,  0.        ],
        [ 0.71428571, -0.44      , -0.46153846,  1.        ]]),
 array([[ 7.        ,  5.        ,  6.        ,  6.        ],
        [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
        [ 0.        ,  0.        , -1.04      ,  3.08      ],
        [ 0.        ,  0.        ,  0.        ,  7.46153846]]))