In [3]:
import numpy as np
import matplotlib.pyplot as plt

# 2.48

In [58]:
def LU_Decomposition(A):
    N = A.shape[0]

    L = np.eye(N)
    U = np.zeros((N,N))
    for i in range(N):
        L[i:,i] = A[i:,i]/A[i,i]
        # print(i,A[i,i])
        U[i,i:] = A[i,i:]

        A[i:,i:] = A[i:,i:] - L[i:,i][:,None]@U[i,i:][None,:]
        # print(A,L[i:,i].reshape([-1,1]).shape,U[i,i:].shape)
    return L,U


In [60]:
A= np.array([[1,1,-1], [1,2,-2.],[-2,1,1]])
L,U = LU_Decomposition(A)
print(L,U)

[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-2.  3.  1.]] [[ 1.  1. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  2.]]
